force-app/main/default/objects/Trivia_Answer_Score__c/Trivia_Answer_Score__c.object-meta.xml
<CustomObject>
    <label>Trivia Answer Score</label>
    <nameField>
        <label>Trivia Answer Score Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Answer Scores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trivia_Answer_Score__c/fields/Score_Points__c.field-meta.xml
<CustomField>
    <fullName>Score_Points__c</fullName>
    <label>Score Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/NTTTriviaAnswerScoreSelector.cls
/**
 * Created by catalinalexandrutanasie on 19.04.23.
 */

public with sharing class NTTTriviaAnswerScoreSelector {
    public static Trivia_Answer_Score__c getScoreSpecForTotalScorePoints(Integer totalScore) {
        for (Trivia_Answer_Score__c tas : [SELECT Score_Points__c, Feedback__c FROM Trivia_Answer_Score__c WHERE Score_Points__c = :totalScore LIMIT 1]) {
            return tas;
        }
        return null;
    }
}