force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>City</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/Is_Test_Run__c.field-meta.xml
<CustomField>
    <fullName>Is_Test_Run__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Test Run</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Office__c/fields/Locations_List__c.field-meta.xml
<CustomField>
    <fullName>Locations_List__c</fullName>
    <label>TriviaLocationsList</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>City</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/Trivia__c.field-meta.xml
<CustomField>
    <fullName>Trivia__c</fullName>
    <label>Trivia</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/NTTOfficeSelector.cls
/**
 * Created by catalinalexandrutanasie on 19.04.23.
 */

public with sharing class NTTOfficeSelector {
    public static Map<Id, Office__c> getOfficeReferenceMap(Boolean isTestContextRun) {
        Map<Id, Office__c> officeMap = new Map<Id, Office__c> ();
        for (Office__c currentOffice : [SELECT Name, City__c, Locations_List__c, Trivia__c FROM Office__c WHERE Is_Test_Run__c = :isTestContextRun]) {
            officeMap.put(currentOffice.Id, currentOffice);
        }
        return officeMap;
    }
}