force-app/main/default/objects/Trivia_Answer__c/Trivia_Answer__c.object-meta.xml
<CustomObject>
    <label>Trivia Answer</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Trivia Answers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trivia Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trivia_Answer__c/fields/Is_Test_Run__c.field-meta.xml
<CustomField>
    <fullName>Is_Test_Run__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Test Run</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trivia_Answer__c/fields/Session_Key__c.field-meta.xml
<CustomField>
    <fullName>Session_Key__c</fullName>
    <externalId>true</externalId>
    <label>Session Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/NTTTriviaAnswerSelector.cls
/**
 * Created by catalinalexandrutanasie on 16.05.23.
 */

public with sharing class NTTTriviaAnswerSelector {
    public static Trivia_Answer__c getProvisionedAnswerForSessionKey(String sessionKey) {
        for (Trivia_Answer__c triviaAnswer : [SELECT Is_Test_Run__c FROM Trivia_Answer__c WHERE Session_Key__c = :sessionKey LIMIT 1]) {
            return triviaAnswer;
        }
        return null;
    }
}