force-app/main/default/objects/Trivia_Answer__c/Trivia_Answer__c.object-meta.xml
<CustomObject>
    <label>Trivia Answer</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Trivia Answers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trivia Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trivia_Answer__c/fields/Is_Test_Run__c.field-meta.xml
<CustomField>
    <fullName>Is_Test_Run__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Test Run</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trivia_Answer__c/fields/Trivia_Answer_Score__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Answer_Score__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trivia Answer Score</label>
    <referenceTo>Trivia_Answer_Score__c</referenceTo>
    <relationshipLabel>Trivia Answers</relationshipLabel>
    <relationshipName>Trivia_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trivia_Answer_Score__c/Trivia_Answer_Score__c.object-meta.xml
<CustomObject>
    <label>Trivia Answer Score</label>
    <nameField>
        <label>Trivia Answer Score Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Answer Scores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trivia_Answer_Score__c/fields/Score_Points__c.field-meta.xml
<CustomField>
    <fullName>Score_Points__c</fullName>
    <label>Score Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/NTTOfficeTriviaServiceComponents.cls
global with sharing class NTTOfficeTriviaServiceComponents {

    global class NTTOfficeListQuestionsResponse {
        global String triviaSessionKey;
        global List<NTTOfficeListQuestionsResponseItem> triviaQuestionList {
            get {
                if (triviaQuestionList == null) {
                    triviaQuestionList = new List<NTTOfficeListQuestionsResponseItem> ();
                }
                return triviaQuestionList;
            }
            set;
        }
    }

    global class NTTOfficeListQuestionsResponseItem {
        global List<String> answerChoices;
        global List<String> publicImageURLList;
        global String triviaHints;
        global String questionReference;
        global NTTOfficeFault fault;

        global NTTOfficeListQuestionsResponseItem(String questionReference, List<String> answerChoices, List<String> publicImageURLList, String triviaHints) {
            this.answerChoices = answerChoices;
            this.publicImageURLList = publicImageURLList;
            this.triviaHints = triviaHints;
            this.questionReference = questionReference;
        }
    }

    global class NTTOfficeTriviaAnswerRequest {
        global String triviaSessionKey;
        global Integer chatGPTCount;
        global Map<String,String> answerMap;
    }

    global class NTTOfficeTriviaAnswerResponse {
        private final String TEST_FEEDBACK = 'This is a test. Normally, here you would see feedback based on your score.';

        global Integer score;
        global String feedback;
        global NTTOfficeFault fault;

        global NTTOfficeTriviaAnswerResponse(Trivia_Answer__c triviaAnswer) {
            this.score = Integer.valueOf(triviaAnswer.Trivia_Answer_Score__r.Score_Points__c);
            this.feedback = triviaAnswer.Is_Test_Run__c ? this.TEST_FEEDBACK : triviaAnswer.Trivia_Answer_Score__r.Feedback__c;
        }

        global NTTOfficeTriviaAnswerResponse(NTTOfficeFault fault) {
            this.fault = fault;
        }
    }

    global class NTTOfficeFault {
        global String exceptionCode;
        global String exceptionMessage;

        global NTTOfficeFault(String code, String message) {
            this.exceptionCode = code;
            this.exceptionMessage = message;
        }
    }
}