force-app/main/default/objects/Trivia_Answer__c/Trivia_Answer__c.object-meta.xml
<CustomObject>
    <label>Trivia Answer</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Trivia Answers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trivia Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trivia_Answer__c/fields/Answers__c.field-meta.xml
<CustomField>
    <fullName>Answers__c</fullName>
    <label>Answers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trivia_Answer__c/fields/Chat_GPT_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Chat_GPT_Attempts__c</fullName>
    <label>Chat GPT Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trivia_Answer__c/fields/Contestant__c.field-meta.xml
<CustomField>
    <fullName>Contestant__c</fullName>
    <label>Contestant</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trivia_Answer__c/fields/Is_Test_Run__c.field-meta.xml
<CustomField>
    <fullName>Is_Test_Run__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Test Run</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trivia_Answer__c/fields/Session_Key__c.field-meta.xml
<CustomField>
    <fullName>Session_Key__c</fullName>
    <externalId>true</externalId>
    <label>Session Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trivia_Answer__c/fields/Trivia_Answer_Score__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Answer_Score__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trivia Answer Score</label>
    <referenceTo>Trivia_Answer_Score__c</referenceTo>
    <relationshipLabel>Trivia Answers</relationshipLabel>
    <relationshipName>Trivia_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trivia_Answer_Score__c/Trivia_Answer_Score__c.object-meta.xml
<CustomObject>
    <label>Trivia Answer Score</label>
    <nameField>
        <label>Trivia Answer Score Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Answer Scores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NTTTriviaAnswerBuilder.cls
/**
 * Created by catalinalexandrutanasie on 19.04.23.
 */

public with sharing class NTTTriviaAnswerBuilder {
    private Trivia_Answer__c record;
    private NTTTriviaAnswerBuilder() {
        this.record = new Trivia_Answer__c();
    }

    private NTTTriviaAnswerBuilder(Trivia_Answer__c answer) {
        this.record = answer;
    }

    public static NTTTriviaAnswerBuilder getBuilder() {
        return new NTTTriviaAnswerBuilder();
    }

    public static NTTTriviaAnswerBuilder getBuilder(Trivia_Answer__c answer) {
        return new NTTTriviaAnswerBuilder(answer);
    }

    public NTTTriviaAnswerBuilder setChatGPTCount(Integer chatGPTCount) {
        this.record.Chat_GPT_Attempts__c = Decimal.valueOf(chatGPTCount);
        return this;
    }

    public NTTTriviaAnswerBuilder setSessionKey(String sessionKey) {
        this.record.Session_Key__c = sessionKey;
        return this;
    }

    public NTTTriviaAnswerBuilder setContestant(String contestant) {
        this.record.Contestant__c = contestant;
        return this;
    }

    public NTTTriviaAnswerBuilder setTriviaAnswerScoreId(Id answerScoreId) {
        this.record.Trivia_Answer_Score__c = answerScoreId;
        return this;
    }

    public NTTTriviaAnswerBuilder setTriviaAnswerScore(Trivia_Answer_Score__c tas) {
        this.record.Trivia_Answer_Score__r = tas;
        return this;
    }

    public NTTTriviaAnswerBuilder setAnswerMap(Map<Id, String> answerMap) {
        this.record.Answers__c = String.valueOf(answerMap);
        return this;
    }

    public NTTTriviaAnswerBuilder setTestContext(Boolean isTestContext) {
        this.record.Is_Test_Run__c = isTestContext;
        return this;
    }

    public Trivia_Answer__c insertRecord() {
        insert this.record;
        return this.record;
    }

    public Trivia_Answer__c updateRecord() {
        upsert this.record;
        return this.record;
    }
}